name: 'Workflow Example'
on:
  workflow_dispatch:

jobs:
  test:
    env:
      ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
      SOME_SECRET: some-secret-value
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create GitHub Repo
        id: create-repo
        uses: ./
        with:
          zipPath: 'examples/test.zip'
          repoName: 'test-repo'
          repoDescription: 'My repo description'
          repoVisibility: 'private'
          securityToken: ${{ secrets.ORG_TOKEN }}
          envsToRepoSecrets: ORG_TOKEN,SOME_SECRET
      - name: Get the repo URL
        run: echo "The repo URL is ${{ steps.create-repo.outputs.repoUrl }}"